# Generated by Django 5.2.6 on 2025-11-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usergallery',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='usergallery',
            name='auto_crop_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergallery',
            name='optimized_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergallery',
            name='original_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
