# Generated by Django 5.2.6 on 2025-11-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usergallery_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergallery',
            old_name='original_image',
            new_name='original_image_url',
        ),
    ]
