# Generated by Django 5.2.6 on 2025-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_original_image_usergallery_original_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergallery',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
