# Generated by Django 5.2.6 on 2025-11-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usergallery_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otphistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP History', 'verbose_name_plural': 'OTP Histories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usergallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'User Gallery', 'verbose_name_plural': 'User Galleries'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='usergallery',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
