# Generated by Django 5.2.6 on 2025-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otphistory_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergallery',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='usergallery',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp_uploads/'),
        ),
    ]
