# Generated by Django 5.2.6 on 2025-10-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('comment', models.CharField(default='Auto Add by System', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_get', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=False)),
                ('can_put', models.BooleanField(default=False)),
                ('can_patch', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_entries', to='coresettings.apis')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access', to='coresettings.role')),
            ],
            options={
                'unique_together': {('role', 'api')},
            },
        ),
    ]
