# Generated by Django 5.2.6 on 2025-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_branch_country_alter_branch_city_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('hotel', 'name'), name='unique_branch_per_hotel'),
        ),
    ]
